server:
  port: 9090

spring:
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password:
      timeout: 20000
      jedis:
        pool:
          max-idle: 6
          max-active: 10
          min-idle: 2